name: Build plugin

on:
  pull_request:
    branches: ["master"]
  release:
    types: ["published"]
  push:
    branches: ["master"]

jobs:
  build:
    name: Build plugin
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Get version
      id: version
      uses: ludeeus/actions-1/helpers/version@master
      with:
        type: plugin

    - name: Initialize git
      if: steps.version.outputs.publish == 'true'
      uses: ludeeus/actions-1/helpers/git-init@master
      with:
        name: ${{ secrets.GIT_NAME }}
        email: ${{ secrets.GIT_EMAIL }}
        token: ${{ secrets.GIT_TOKEN }}
    
    - name: Login to DockerHub
      if: steps.version.outputs.publish == 'true'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set build arguments
      if: steps.version.outputs.publish == 'false'
      run: echo "BUILD_ARGS=--test" >> $GITHUB_ENV

#    - name: Build plugin
#      uses: home-assistant/builder@2020.10.0
#      with:
#        args: |
#          $BUILD_ARGS \
#          --all \
#          --target /data \
#          --generic ${{ steps.version.outputs.version }} \
#          --docker-hub ludeeus

    - name: Update version file
      if: steps.version.outputs.publish == 'true'
      uses: ludeeus/actions-1/helpers/version-push@master
      with:
        key: observer
        version: ${{ steps.version.outputs.version }}
        channel: ${{ steps.version.outputs.channel }}